### ISSUE TITLE
Create Design Competition part of the website

### ISSUE THREAD

**Issue by TristanTjan** [acmucsd/main-website#173]
Fall Design's 2021:
https://drive.google.com/drive/folders/1VcSDOvMDxYESjS8Lu-WVgS5gWpH2C223QcBjsBr8ML3gVHtSrgPJYLN3bwqe3o9VEwe9m1h5?usp=sharing

Winter Design's 2022:
https://drive.google.com/drive/folders/1kow6IvlQt4fTU7YD98pi3YjE14f1BThUzZja6vTM9EOUFNKs8NaYUKg74oCviZs_eDWeJZbQ?usp=sharing

**Comment by TristanTjan** [comment]
@steets250

**Comment by TristanTjan** [comment]
I expect results

**Comment by steets250** [comment]
@shirley plz do
