### ISSUE TITLE
Remove Horizontal Scrollbar on Community Page

### ISSUE THREAD

**Issue by leestanley** [acmucsd/main-website#178]
A horizontal scrollbar appears on the acmucsd.com/communities page

On a 1920x1080 monitor

![image](https://user-images.githubusercontent.com/8893880/151094350-bcf8921e-7550-4333-a243-e9cbc41b23fe.png)

**Comment by trulyronak** [comment]
@farisashai is this still an issue?

**Comment by trulyronak** [comment]
@leestanley do you get this issue still on your display - we can't recreate
