### ISSUE TITLE
Add Website Link Previews

### ISSUE THREAD

**Issue by leestanley** [acmucsd/main-website#182]
Currently, when you post our website on any social media platform, there's no link preview for what it might contain. This can be done with meta tags or some 3rd party npm package

Example of using meta tags:
https://github.com/leestanley/personal-site-v2/blob/master/public/index.html

![image](https://user-images.githubusercontent.com/8893880/151909941-9253dd9f-3152-49c8-87f7-a38d954610b7.png)

Our website:
![image](https://user-images.githubusercontent.com/8893880/151909618-14135e6d-a022-4c3e-8225-ea7ee9c6db93.png)

Github's:
![image](https://user-images.githubusercontent.com/8893880/151909629-6df09f42-53b1-4f92-80f9-4d6b6074dc24.png)

**Comment by farisashai** [comment]
added some meta tags we can replace per page in the SEO component in [next rewrite](https://acmucsd.vercel.app/)
<img width="581" alt="Screen Shot 2022-02-11 at 11 10 46 PM" src="https://user-images.githubusercontent.com/33165426/153701194-e0efb551-bd52-4bfc-8bbb-19090afbd0bb.png">
