### ISSUE TITLE
Events row overflows to edge of screen

### ISSUE THREAD

**Issue by duanwilliam** [acmucsd/main-website#184]
![image](https://user-images.githubusercontent.com/38791932/151918582-6a38904a-0f5b-4b54-a64e-beb1d9e3d84d.png)

We would probably want website content to be wrapped in some horizontal padding. i believe modifying the horizontal padding here to 1rem or something should fix it.

https://github.com/acmucsd/main-website/blob/1073c8860c29bab6c7bd77eed7174c0a34f28f1b/src/components/Layout/index.js#L33-L38

(also, on the topic of that, (1) the values for vertical padding / min height / seem kinda arbitrary + prob want the content width value defined as a constant somewhere and (2) why are the styles inlined)

**Comment by WishingWell13** [comment]
<img width="1065" alt="image" src="https://github.com/user-attachments/assets/c0ea9af2-f7ea-4336-8f80-cb893b3625d7" />
<img width="323" alt="image" src="https://github.com/user-attachments/assets/c4b3cbe8-9e94-49ca-ae1b-83df263b7e9b" />


Looks like it got fixed somewhere in these 3 years.
