### ISSUE TITLE
Improve Communities Page Responsiveness on Mobile

### ISSUE THREAD

**Issue by leestanley** [acmucsd/main-website#194]
If you go on the mobile view on Sponsor page, there's a large white space on the bottom. 
![image](https://user-images.githubusercontent.com/8893880/153692961-db7056a0-c8ee-483d-9460-b289d63c82ec.png)

Once you click on one of the communities, you need to scroll down, select a community, then scroll back up to read the text. We can just move the community logos to the top so you can cycle through them without having to scroll all the way down again. 
![image](https://user-images.githubusercontent.com/8893880/153692915-f90baf99-1f11-4a61-8c13-25dd9db1509e.png)

**Comment by farisashai** [comment]
i fixed this on the [next rewrite](https://acmucsd.vercel.app/communities) lmk how it looks

**Comment by leestanley** [comment]
> i fixed this on the [next rewrite](https://acmucsd.vercel.app/communities) lmk how it looks 

Looking good, hover effect on the communities feel a bit weird but that can be a separate issue. Feel free to close this issue on the PR.
