### ISSUE TITLE
Match Portal Header Sizing

### ISSUE THREAD

**Issue by steets250** [acmucsd/main-website#210]
The header height for the main website should be 68px tall total, with 64px height of content area and then 4px height of rainbow bar. This will match the existing membership portal and create a smoother transition between the two sites.

See here for exact specs: https://www.figma.com/file/qnePIhNiU8R0jdDc1h7tpp/The-ACM-Store?node-id=948%3A2355

**Comment by trulyronak** [comment]
new take - don't worry about adjusting the size
