### ISSUE TITLE
Inconsistent padding on Board Pictures organization selection buttons

### ISSUE THREAD

**Issue by trulyronak** [acmucsd/main-website#217]
![image](https://user-images.githubusercontent.com/28539155/156505865-75a5cc27-44e9-4c50-b509-8344bc6b2700.png)

e.g. the horizontal padding on the "hack" button is smaller than for "ai"

referencing the issue (https://github.com/acmucsd/membership-portal-ui/issues/546) created by @alistairgray42

**Comment by farisashai** [comment]
Resolved in #263
